- app/scripts/controllers/loginController.js
- app/scripts/controllers/userTimesheetController.js
- app/scripts/services/userServices.js
- app/views/_usertimesheet.html
> api integration

- app/scripts/controllers/detailViewController.js
- app/scripts/controllers/forgotPasswordController.js
- app/scripts/controllers/loginController.js
- app/scripts/controllers/signUpController.js
- app/scripts/controllers/userTimesheetController.js
- app/scripts/controllers/verifyUserController.js
- app/scripts/services/UserService.js
- app/views/_detailview.html
- app/views/_signup.html
> formatting of controller and services

- gulpfile.js
> structured the gulp file with required plughins

- app/index.html
- app/scripts/app.js
- app/scripts/controllers/loginController.js
- app/scripts/controllers/userTimesheetController.js
- app/scripts/httpRequest.js
- app/scripts/services/AuthService.js
- app/scripts/services/UserService.js
- app/views/_usertimesheet.html
1) auth changes
2) Timesheet changes
> auth sevice changes

- app/scripts/controllers/detailViewController.js
- app/scripts/controllers/signUpController.js
- app/scripts/services/UserService.js
- app/views/_detailview.html
- app/views/_signup.html
Sir,
connect #31 
Please review and merge
> #31 timesheet detail functionality

- app/scripts/controllers/userTimesheetController.js
- app/scripts/services/UserService.js
- app/views/_usertimesheet.html
> code optimizaton and change the view of date

- bower.json
Please review and merge the changes
connect #37
> #37 structure bower

- app/assets/styles/style.scss
- app/assets/styles/variable.scss
- app/scripts/app.js
- app/scripts/controllers/detailViewController.js
- app/scripts/controllers/signUpController.js
- app/scripts/controllers/verifyUserController.js
- app/scripts/services/AuthService.js
- app/views/_detailview.html
- app/views/_signup.html
- app/views/_verifyuser.html
Please review and merge the changes
> issue36 User verification

- app/scripts/controllers/loginController.js
- app/scripts/controllers/userTimesheetController.js
- app/scripts/services/UserService.js
- app/views/_login.html
- app/views/_usertimesheet.html
> implement monthly timesheet view and weekly view

- app/scripts/controllers/userTimesheetController.js
- app/scripts/services/UserService.js
- app/views/_usertimesheet.html
Please merge.
connects issue #45
> email timesheet to register mail id

- app/assets/styles/style.css
- app/assets/styles/style.scss
- app/scripts/app.js
- app/scripts/controllers/forgotPasswordController.js
- app/scripts/services/UserService.js
- app/views/_forgotpassword.html
- app/views/_resetpassword.html
Please review and merge.
connect #47
> forgot password functionality

- app/assets/styles/style.css
- app/assets/styles/style.scss
- app/scripts/controllers/forgotPasswordController.js
- app/scripts/services/UserService.js
- app/views/_forgotpassword.html
- app/views/_login.html
- app/views/_resetpassword.html
- app/views/_signup.html
Please review and merge 
Forgot password verification and recover
> forgotpassword recover& verification

- gulpfile.js
> vendor script added moment.js

- app/assets/styles/style.css
- app/index.html
- app/scripts/app.js
- app/scripts/controllers/detailViewController.js
- app/scripts/controllers/userTimesheetController.js
- app/scripts/services/UserService.js
- app/views/_usertimesheet.html
- gulpfile.js
> timesheet editview

- app/scripts/controllers/detailViewController.js
- app/scripts/services/UserService.js
> edit changes

- app/scripts/controllers/detailViewController.js
- app/scripts/services/UserService.js
- app/scripts/services/httpProvider.js
- app/views/_detailview.html
- app/views/_signup.html
- gulpfile.js
> centralized header

- app/scripts/controllers/detailViewController.js
- app/scripts/controllers/signUpController.js
- app/scripts/services/UserService.js
- app/views/_detailview.html
> edit view changes

- gulpfile.js
> user service provider now available

- app/scripts/services/AuthService.js
- app/scripts/services/UserService.js
Please review and merge the branch
> removed static token and userdata

- .scss-lint.yml
- package.json
connects #51 
I am going to merge this on monday
> Added pre commit hooks

- app/scripts/app.js
- app/scripts/controllers/userTimesheetController.js
> year filteration are on the basis of Doj

- app/scripts/app.js
- app/scripts/controllers/detailViewController.js
- app/scripts/controllers/userTimesheetController.js
- app/views/_detailview.html
> backdates data is in readonly formt with correct tmings

- app/assets/styles/style.css
- app/assets/styles/style.scss
- app/views/_detailview.html
- app/views/_forgotpassword.html
> ui changes for login and forgot layout

- app/assets/styles/style.scss
- app/index.html
- app/scripts/app.js
- app/scripts/controllers/detailViewController.js
- app/scripts/controllers/loginController.js
- app/scripts/controllers/signUpController.js
- app/scripts/controllers/userTimesheetController.js
- app/scripts/controllers/verifyUserController.js
- app/scripts/directives/formFieldDirectives.js
- app/scripts/services/AuthService.js
- app/scripts/services/UserService.js
- app/scripts/services/httpProvider.js
- app/scripts/services/httpRequest.js
- app/views/_detailview.html
- app/views/_forgotpassword.html
- app/views/_login.html
- app/views/_resetpassword.html
- app/views/_signup.html
- app/views/_verifyuser.html
- web-server.js
@deeppatidar @varshatyagi 
1. I have fixed most of the eslint errors, so please run `eslint app/scripts/` fixed the remaining errors.
2. I have also made some UI changes in this code.
After fixing errors please make sure that this code is not breaking any where, i am not able to test it completely as backend api's are not working.
> dont merge - UI and linting fixes

- app/assets/styles/style.scss
- app/assets/styles/variable.scss
> moved variables

- app/scripts/app.js
- app/scripts/controllers/userTimesheetController.js
- app/scripts/services/UserService.js
- app/views/_usertimesheet.html
connects #46 
weekly view issue , also fixed.
> export timesheet functionality

- app/scripts/controllers/userTimesheetController.js
- app/views/_usertimesheet.html
> show availblity message for no timesheet data

- app/scripts/controllers/userTimesheetController.js
- app/views/_usertimesheet.html
> Updation in email popup box

- app/assets/styles/style.scss
- app/scripts/app.js
- app/scripts/controllers/signUpController.js
- app/scripts/services/UserService.js
- app/views/_signup.html
> 95 unable register

- app/scripts/app.js
- app/scripts/controllers/forgotPasswordController.js
- app/views/_forgotpassword.html
- app/views/_resetpassword.html
> forget password issue

- app/scripts/directives/formFieldDirectives.js
- app/views/_signup.html
> 90 error message

- app/scripts/app.js
- app/scripts/controllers/userTimesheetController.js
- app/views/_usertimesheet.html
1) No data message will show when data is not available for a month in a respective year.
2) If the month is the current month of the year then no data message will not show, even if the data is not available.
connects #96
> timesheet no availablity data issue

- app/scripts/controllers/signUpController.js
- app/views/_signup.html
> 93-registration form reset issue

- app/assets/styles/style.scss
- app/scripts/controllers/verifyUserController.js
- app/views/_verifyuser.html
- gulpfile.js
> user verified

- app/views/_detailview.html
> 114-work description issue

- app/assets/styles/style.scss
- app/index.html
- app/scripts/app.js
- app/scripts/controllers/detailViewController.js
- app/scripts/controllers/signUpController.js
- app/views/_detailview.html
- app/views/_signup.html
> 113-total-hours-issue

- app/scripts/controllers/loginController.js
- app/scripts/controllers/userTimesheetController.js
- app/views/_login.html
> login and timesheet issue

- app/scripts/app.js
- app/scripts/controllers/detailViewController.js
- app/scripts/controllers/signUpController.js
- app/scripts/controllers/verifyUserController.js
- app/views/_detailview.html
- app/views/_login.html
- app/views/_signup.html
- app/views/_verifyuser.html
Please review and merge the branch
> 119 verification issue

- app/scripts/controllers/datePickerController.js
- app/scripts/controllers/signUpController.js
- app/scripts/controllers/userTimesheetController.js
- app/views/_signup.html
- gulpfile.js
> date picker issue resolved

- app/scripts/app.js
- app/scripts/services/UserService.js
> 132 loggedin issue

- app/views/_usertimesheet.html
> 128-short description on icon

- app/assets/styles/style.scss
- app/views/_signup.html
> datepicker layout updated

- app/scripts/controllers/userTimesheetController.js
- app/views/_usertimesheet.html
> resolved timesheet issue

- app/index.html
- app/scripts/controllers/detailViewController.js
- app/views/_detailview.html
- app/views/_signup.html
> 144-detail-error-handling

- app/scripts/controllers/detailViewController.js
- app/scripts/services/UserService.js
- app/views/_detailview.html
Please review and merge the branch
> 157-detail-page xml error

- app/scripts/controllers/userTimesheetController.js
- app/views/_usertimesheet.html
> icons are disable

- app/views/_signup.html
> 91-text-limit

- app/scripts/controllers/detailViewController.js
- app/views/_detailview.html
> 146-wrok-description-validation

- app/assets/styles/style.scss
- app/views/_detailview.html
> 147 total hours

- app/scripts/controllers/detailViewController.js
- app/scripts/controllers/forgotPasswordController.js
- app/scripts/controllers/loginController.js
- app/scripts/controllers/signUpController.js
- app/scripts/controllers/userTimesheetController.js
- app/views/_detailview.html
- app/views/_forgotpassword.html
- app/views/_login.html
- app/views/_resetpassword.html
- app/views/_signup.html
- app/views/_usertimesheet.html
> handle the un neccessary request and show loading indicator

- app/scripts/controllers/userTimesheetController.js
- app/views/_usertimesheet.html
> icons will be disabled for current month, when no data availble

- app/scripts/controllers/detailViewController.js
- app/views/_detailview.html
- app/views/_signup.html
> 151-lunch-time-issue

- app/scripts/controllers/detailViewController.js
- app/views/_detailview.html
> Detail changes

- app/scripts/controllers/detailViewController.js
- app/views/_signup.html
> detail-error

- app/scripts/controllers/verifyUserController.js
- app/views/_verifyuser.html
> ui updated

- app/scripts/controllers/signUpController.js
> button is enabled again

- app/scripts/controllers/userTimesheetController.js
> no values are showing as null values

- app/assets/styles/style.scss
- app/assets/styles/variable.scss
- app/index.html
- app/scripts/app.js
- app/scripts/controllers/logoutController.js
- app/scripts/controllers/userTimesheetController.js
- app/views/_usertimesheet.html
- gulpfile.js
> ui changes

- app/scripts/controllers/signUpController.js
> user will not register after reset of data

- app/index.html
- app/views/_detailview.html
- app/views/_signup.html
> no login details will show in registration page

- app/scripts/controllers/detailViewController.js
- app/views/_detailview.html
> 156-input-value

- app/scripts/controllers/detailViewController.js
> 195-input-issue

- app/views/_detailview.html
> 151-night-time-error

- app/scripts/app.js
- app/scripts/controllers/userTimesheetController.js
- app/views/_usertimesheet.html
> add character limit

- app/views/_usertimesheet.html
- bower.json
- gulpfile.js
> use font awesome for font icons

- app/scripts/controllers/userTimesheetController.js
connect #204 
I have added the flag to the new entries. Now you can set the default entries to the detail view.
> add default data to every new entry for timesheet

- gulpfile.js
> font icons added

- app/index.html
- app/scripts/controllers/userTimesheetController.js
> add limit to description

- app/scripts/app.js
- app/scripts/services/AuthService.js
> set cookie expire time

- app/scripts/app.js
> updated length of description

- app/index.html
- app/scripts/controllers/detailViewController.js
- app/views/_detailview.html
> 212-char-limit

- app/index.html
- app/scripts/controllers/detailViewController.js
> 214-default-entry

- app/scripts/controllers/detailViewController.js
Please merge
Total hour changes
> 204-default-entry

- gulpfile.js
> add missing datepicker icons

- app/scripts/services/AuthService.js
- app/scripts/services/UserService.js
> 222-login issue

- app/scripts/controllers/detailViewController.js
- app/scripts/controllers/userTimesheetController.js
> 224-cookies-expire

- app/scripts/app.js
- app/scripts/controllers/userTimesheetController.js
- app/scripts/services/httpProvider.js
- app/scripts/services/httpRequest.js
> handle bad request

- app/scripts/app.js
- app/scripts/controllers/userTimesheetController.js
- app/scripts/services/httpRequest.js
> updation in dropdown option

- app/scripts/app.js
- app/scripts/controllers/userTimesheetController.js
- app/views/_detailview.html
> 234-highlight-edited-row

- app/scripts/controllers/detailViewController.js
- app/views/_detailview.html
> 234 highlight edited row

- app/views/_usertimesheet.html
> add hover action

- app/views/_signup.html
> 240-error-message-on-signup

- app/scripts/controllers/loginController.js
> redirect to default page

- app/scripts/controllers/detailViewController.js
- app/scripts/controllers/userTimesheetController.js
- app/views/_signup.html
- app/views/_usertimesheet.html
> highlighted edited row

- app/scripts/controllers/verifyUserController.js
> modify copy change

- app/scripts/controllers/detailViewController.js
> 249-email-notification-link-issue

- app/views/_usertimesheet.html
> update status of edit row

- app/views/_usertimesheet.html
> updated rows color

- app/assets/styles/style.scss
- app/assets/styles/variable.scss
- app/scripts/controllers/signUpController.js
- app/views/_usertimesheet.html
> color updated

- app/scripts/controllers/loginController.js
> issue resolve

- app/views/_usertimesheet.html
> 219-total-hours-on-timesheet
